name: Build and test action

on:
  push:
    branches: [main]
    paths: [hello-world-docker-action/**]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run Action
        id: hello-world-docker-action
        uses: ./hello-world-docker-action
        with:
          message: 'Hello from Docker'
      
      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-world-docker-action.outputs.time }} when the action said hello"
          
