name: Github Actions Demo

on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select environment
        default: Test
  
jobs:

  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Output the name of the event that triggered the workflow
        run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
      - name: Output the name of the current branch
        run: |
           echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: List all repo files
        run: |
          ls -la

  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - run: echo "🧪 Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load-Test
    steps:
      - run: |
          echo "🧪 Testing..."
          sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: |
          echo "🚀 Step 1..."
          sleep 10
      - run: |
          echo "🚀 Step 2..."
          sleep 10
      - run: |
          echo "🚀 Step 3..."
          sleep 10
      - run: |
          echo "🚀 Step 4..."
          sleep 10
      - run: |
          echo "🚀 Step 5..."
          sleep 10
