name: Reusable Workflow

on:
  workflow_call:
    inputs:
      message:
        description: Input Message for the hello from docker workflow
        type: string
        required: true
        default: world
    outputs:
      current-time:
        description: "The time when greeting."
        value: ${{ jobs.reusable-job.outputs.current-time }}

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: greet
        run: echo ${{inputs.message}}
      - name: set time
        id: time
        run: echo time=$(date) >> $GITHUB_OUTPUT
